from pathlib import Path
from html import escape as E
import json
R=Path(__file__).resolve().parent
css='''body{margin:0;background:#f5f1e9;color:#292b2a;font:17px/1.65 system-ui}main,header,footer{max-width:850px;margin:auto;padding:22px}h1,h2,h3{font-family:Georgia,serif;line-height:1.2}h1{font-size:clamp(32px,6vw,52px)}a{color:#325550}section,article{border:1px solid #cdc9c0;background:#fffdf8;border-radius:12px;padding:22px;margin:18px 0}input,select,textarea,button{font:inherit;box-sizing:border-box;max-width:100%}input,textarea,select{width:100%;padding:10px;border:1px solid #797e77;border-radius:6px;background:#fff;color:#242824}label{display:block;margin:12px 0}button,.button{display:inline-block;padding:10px 16px;background:#325550;color:white;border:0;border-radius:6px;cursor:pointer;margin:6px 4px 6px 0}button:focus-visible,a:focus-visible{outline:3px solid #a75428;outline-offset:3px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#ede9e1;padding:14px;font:15px/1.6 system-ui}img{width:100%;height:auto;border-radius:8px}nav{display:flex;gap:18px;flex-wrap:wrap}.muted{color:#535952}*{box-sizing:border-box}output{font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}@media(max-width:500px){main,header,footer{padding:16px}section,article{padding:16px}}@media print{nav,button{display:none}section{break-inside:avoid}}'''
def page(name,title,body,script=''):
 (R/name).write_text(f'<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} · Monetização v6.2</title><style>{css}</style></head><body><header><nav><a href="curso.html#trilha">Curso</a><a href="caderno.html">Fichas e proposta</a><a href="calculadora.html">Calculadora</a><a href="abordagens.html">20 abordagens</a></nav></header><main><p>INEMA.CLUB · Monetização v6.2</p><h1>{E(title)}</h1>{body}</main><footer><a href="https://inema.club">Voltar ao portal INEMA.CLUB</a></footer><script>{script}</script></body></html>')
rows=[
('Apresentação a um ateliê','Canal comercial que recebe propostas.','Sou [nome] e produzo [serviço]. Vi [fato verificado] no ateliê. Tenho um estudo próprio sobre [necessidade]. Posso enviar o exemplo para você avaliar?'),
('Resposta a pedido público','A empresa publicou que procura esse serviço.','Vi seu pedido de [entrega]. Trabalho com [escopo] e tenho um exemplo pertinente. Qual é o uso previsto e o prazo desejado?'),
('Indicação autorizada','A pessoa citada autorizou a indicação.','[Pessoa] autorizou mencionar que seu projeto precisa de [serviço]. Sou [nome]. Faz sentido conversarmos sobre quantidade, uso e prazo?'),
('Contato já conhecido','Vocês já conversaram de verdade.','Na nossa conversa sobre [assunto], você comentou [necessidade]. Preparei um estudo autoral relacionado. Gostaria de vê-lo?'),
('Evento profissional','Houve conversa real no evento.','Conversamos em [evento] sobre [tema]. Você pediu que eu retomasse o contato. Posso compartilhar uma referência do meu trabalho?'),
('Nova coleção','Lançamento observado, sem supor interesse.','Vi a apresentação de [coleção]. Produzo vídeos curtos de detalhes de produto. Tenho um estudo identificado como fictício; posso mostrar para você avaliar o formato?'),
('Resposta a orçamento solicitado','A pessoa pediu uma estimativa.','Para estimar [entrega], preciso confirmar quantidade, duração, uso e prazo. Quem aprova as etapas e quais materiais já estão disponíveis?'),
('Envio solicitado de portfólio','Houve pedido ou concordância para receber.','Conforme você pediu, segue [endereço conferido]. Separei três peças relacionadas a [necessidade]. Minha participação e a origem dos materiais estão descritas em cada exemplo.'),
('Esclarecimento de uso','Conversa de orçamento já em andamento.','O vídeo será usado apenas no perfil da marca ou também em anúncio pago? Essa diferença afeta permissões e condições da proposta.'),
('Esclarecimento de prazo','Falta informação para estimar agenda.','Qual data atende ao projeto? Para confirmar disponibilidade, preciso considerar recebimento dos materiais, aprovação e revisão. Posso verificar após essas definições.'),
('Alternativa de escopo','Investimento informado não cobre opção inicial.','Com esse investimento, posso estudar uma entrega menor: [escopo]. Ela retira [itens] e preserva [critérios]. Quer comparar essa alternativa com a proposta inicial?'),
('Piloto limitado','Interesse em uma etapa de avaliação.','Podemos definir um piloto pago de [entrega], com [revisão] e [uso]. Ele não implica uma série automática. Posso detalhar custo e critérios de aprovação?'),
('Retomada combinada','Data de retorno acordada anteriormente.','Combinamos retomar em [data] após [etapa]. Você já tem as informações necessárias para avançarmos? Se o projeto mudou, posso atualizar a situação.'),
('Retomada pontual pertinente','Avaliar canal e contexto; nunca após recusa.','Retomo uma única vez a proposta de [assunto] para saber se ainda faz sentido. Se não for o momento, encerro por aqui. Não é necessário justificar.'),
('Pedido de informação faltante','Proposta em preparação, sem urgência inventada.','Falta confirmar [informação] para concluir a estimativa. Quando você puder enviar, reviso o escopo. O prazo de produção ainda depende dessa definição.'),
('Recebimento de comentários','Cliente enviou uma rodada de revisão.','Recebi os comentários. Vou consolidá-los em [lista] e conferir quais estão no escopo. Antes de executar algo adicional, envio o impacto para aprovação.'),
('Mudança de escopo','Pedido novo excede condições combinadas.','A inclusão de [item] acrescenta [trabalho ou direito]. Vou estimar o impacto em prazo e valor. A versão original continua sendo [escopo].'),
('Recusa por capacidade','Você não consegue cumprir prazo ou escopo.','Obrigado por explicar o projeto. Não consigo assumir [condição] com a qualidade necessária neste prazo. Prefiro deixar esse limite claro antes da contratação.'),
('Encerramento respeitoso','Pessoa recusou ou pediu para parar.','Entendido. Vou encerrar este contato e respeitar seu pedido. Obrigado pelo retorno.'),
('Entrega e continuidade opcional','Entrega real concluída e conferida.','A entrega combinada está em [endereço verificado], com [arquivos]. Confira pelos critérios acordados. Se surgir uma nova necessidade, podemos avaliar um escopo separado.')]
body='<p>Vinte situações autorais para treino. Não são uma lista de contatos nem uma sequência de disparos. Leia todas, adapte três e mantenha como rascunho. Use apenas fatos verdadeiros; respeite o canal e pedidos para parar.</p>'
for i,(name,condition,msg) in enumerate(rows,1):body+=f'<article><h2>{i:02d}. {E(name)}</h2><p><b>Quando faz sentido:</b> {E(condition)}</p><pre>{E(msg)}</pre><p>Situação do exercício: rascunho. Nenhuma mensagem foi enviada.</p></article>'
page('abordagens.html','20 abordagens com contexto',body)
(R/'context/abordagens.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
body='''<p>Simulador de orçamento para comparar premissas. Não define preço de mercado, tributos devidos ou lucro garantido. Inclua todos os custos e confirme as taxas aplicáveis à sua situação. Não há pagamentos nesta página.</p><section><h2>Premissas do exemplo</h2><p>Hora de referência: remuneração planejada de R$ 2.400 dividida por 40 horas faturáveis = R$ 60/h. São valores fictícios. Horas faturáveis não são todas as horas trabalhadas.</p><label>Carregar exemplo<select id="pacote"><option value="A">A · uma peça</option><option value="B">B · três peças</option><option value="C">C · cinco peças e capas</option></select></label><div class="grid">'''
fields=[('horas','Horas estimadas',6),('hora','Custo da hora (R$)',60),('diretos','Despesas diretas (R$)',90),('fixos','Parcela de custos fixos (R$)',150),('taxas','Taxas sobre receita (%)',10),('margem','Margem desejada sobre receita (%)',20)]
for key,label,val in fields:body+=f'<label>{label}<input id="{key}" type="number" min="0" step="0.01" value="{val}"></label>'
body+='''</div><p>Taxas de 10% e margem de 20% são premissas didáticas. O campo de taxas agrega percentuais incidentes sobre a receita neste modelo simplificado. Despesas fixas por operação entram em despesas diretas, sem duplicar custos.</p><p id="erro" role="status"></p><p>Custo total: <output id="custo"></output></p><p>Preço calculado: <output id="preco"></output></p><p>Taxas estimadas: <output id="valor-taxas"></output></p><p>Saldo após custos e taxas: <output id="saldo"></output></p><p>Margem calculada: <output id="margem-real"></output></p><p id="formula"></p><button id="imprimir" type="button">Imprimir ou salvar cálculo em PDF</button><p>A página não salva os campos após fechar. Preserve o cálculo pela impressão ou copie as premissas para sua ficha.</p></section><section><h2>Como interpretar</h2><p>Custo = horas × custo da hora + despesas diretas + parcela fixa. Preço = custo ÷ (1 − taxas − margem), com percentuais convertidos em frações.</p><p>No exemplo A: R$ 600 ÷ 0,70 = aproximadamente R$ 857,14. Acrescentar apenas 20% ao custo produziria outro resultado. O saldo só representa a margem prevista se todos os custos e taxas relevantes estiverem incluídos.</p><p>Base B: 14 × 60 + 180 + 150 = R$ 1.170. Base C: 22 × 60 + 270 + 150 = R$ 1.740. Com as mesmas premissas, preços aproximados de R$ 1.671,43 e R$ 2.485,71. São exemplos de orçamento, sem recomendação de cobrança.</p><p>Se taxas mais margem chegarem a 100%, a fórmula não tem preço válido. Valores ausentes, negativos ou não finitos também não produzem resultado.</p></section>'''
script=r'''const ids=['horas','hora','diretos','fixos','taxas','margem'];const $=id=>document.getElementById(id);const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});function calc(){const raw=ids.map(id=>$(id).value);const v=raw.map(Number);const out=['custo','preco','valor-taxas','saldo','margem-real'];if(raw.some(x=>x.trim()==='')||v.some(x=>!Number.isFinite(x)||x<0)||v[4]+v[5]>=100){out.forEach(id=>$(id).textContent='Não disponível');$('formula').textContent='';$('erro').textContent='Preencha valores não negativos. Taxas mais margem devem ser menores que 100%.';return;}const [h,r,d,f,t,m]=v,c=h*r+d+f,p=c/(1-(t+m)/100),tax=p*t/100,s=p-c-tax;if(![c,p,tax,s].every(Number.isFinite)){out.forEach(id=>$(id).textContent='Não disponível');$('formula').textContent='';$('erro').textContent='Valores grandes demais para este cálculo.';return;}$('erro').textContent=c===0?'Custo zero: confira se faltou incluir trabalho ou despesas.':'';$('custo').textContent=money(c);$('preco').textContent=money(p);$('valor-taxas').textContent=money(tax);$('saldo').textContent=money(s);$('margem-real').textContent=p>0?(s/p*100).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%':'Não disponível';$('formula').textContent=money(c)+' ÷ '+(1-(t+m)/100).toLocaleString('pt-BR',{maximumFractionDigits:4})+' = '+money(p);}ids.forEach(id=>$(id).addEventListener('input',calc));$('pacote').addEventListener('change',()=>{const v={A:[6,60,90,150,10,20],B:[14,60,180,150,10,20],C:[22,60,270,150,10,20]}[$('pacote').value];ids.forEach((id,i)=>$(id).value=v[i]);calc();});$('imprimir').addEventListener('click',()=>window.print());calc();'''
page('calculadora.html','Calcule a partir do trabalho',body,script)
body='''<p>Fichas do caso fictício Estúdio Linha e marca Bruma. Copie para suas notas. Materiais de estudo não comprovam contratação, receita ou execução de peças.</p><section id="pesquisa"><h2>Três ofertas públicas, três escopos diferentes</h2><p>Consulta em 25/09/2026. Valores anunciados pelos próprios fornecedores, sujeitos a alteração. Não houve contato, contratação ou avaliação de qualidade. A amostra não representa o mercado e não permite uma média útil.</p><article><h3>Nicolly Braga · R$ 199</h3><p>Starter: um vídeo UGC de até 60 segundos, duas fotos, roteiro básico e uso por três meses. Confira condições e revisões com a fornecedora.</p><a href="https://www.nicollybraga.com/" target="_blank" rel="noopener">Oferta na página da fornecedora</a></article><article><h3>Interagilis · R$ 250</h3><p>Post Social I: vídeo de 15 segundos com avatar de banco, roteiro e edição. A página consultada não esclareceu todos os limites de revisão e licença.</p><a href="https://interagilis.com.br/avatar-ai/" target="_blank" rel="noopener">Oferta na página do fornecedor</a></article><article><h3>SB Studio · R$ 250</h3><p>Essencial: vídeo com IA de até 30 segundos, roteiro e prazo anunciado de três a cinco dias úteis. Há divergência: um trecho anuncia duas revisões; a FAQ menciona uma para esse pacote. Direitos de uso precisam de confirmação.</p><a href="https://sbstudioslz.com.br/" target="_blank" rel="noopener">Oferta e FAQ do fornecedor</a></article><p>Compare quantidade, duração, técnica, revisão, licença e dependências. Valores menores ou maiores não provam equivalência de serviço. Não reproduza promessas de vendas desses anúncios como resultado demonstrado.</p></section>
<section><h2>Três pacotes do exercício</h2><p>Valores fictícios calculados com taxas agregadas de 10% e margem de 20%. Confira suas próprias condições na calculadora.</p><article><h3>A · uma peça</h3><p>Um vídeo vertical de 15 segundos, uma rodada consolidada. Base: R$ 600. Preço simulado: R$ 857,14.</p></article><article><h3>B · três peças</h3><p>Três vídeos verticais de 15 segundos, duas rodadas consolidadas para a série. Base: R$ 1.170. Preço simulado: R$ 1.671,43.</p></article><article><h3>C · cinco peças e capas</h3><p>Cinco vídeos verticais de 15 segundos e uma capa por vídeo, duas rodadas para a série. Base: R$ 1.740. Preço simulado: R$ 2.485,71.</p></article><p>Comum: roteiro, edição, voz autorizada quando usada e MP4. Uso orgânico nos canais da marca por 30 dias, território a definir. Exclui filmagem presencial, tradução, arquivos editáveis e mídia paga. Direitos de terceiros precisam permitir o uso combinado.</p></section>
<section id="plano"><h2>Portfólio em sete dias</h2><ol><li>Definir oferta e critérios das três peças.</li><li>Selecionar arquivos existentes e conferir permissões.</li><li>Corrigir a primeira peça.</li><li>Corrigir a segunda peça.</li><li>Corrigir a terceira peça.</li><li>Montar PDF, contexto e endereços.</li><li>Abrir tudo no celular e revisar clareza.</li></ol><p>Reserve 12–18 horas para o curso com peças existentes. Se precisar produzir do zero, estenda o plano. Sete dias é uma organização sugerida, não uma promessa de produção ou cliente.</p></section>
<section id="proposta"><h2>Modelo de proposta para estudo</h2><pre>Projeto e data:
Situação: rascunho de estudo
Público e necessidade:
Oferta em uma frase:
Exemplo pertinente e sua participação:
Pacote A — quantidade, duração, arquivos, revisão, uso e preço:
Pacote B — quantidade, duração, arquivos, revisão, uso e preço:
Pacote C — quantidade, duração, arquivos, revisão, uso e preço:
Premissas do cálculo e custos incluídos:
Materiais fornecidos pelo cliente:
Quem aprova e em quais etapas:
Marco inicial do prazo e disponibilidade a confirmar:
Exclusões e tratamento de mudanças:
Direitos — canais, período, território, mídia paga e terceiros:
Condições de pagamento e validade a definir:
Pendências contábeis, contratuais e de autorização:
Próxima revisão:</pre><p>Este modelo organiza informações. Não é um contrato completo nem define obrigações universais. Antes de contratar, adapte à situação e obtenha a orientação necessária.</p></section>
<section><h2>Acompanhamento mínimo · dados fictícios</h2><pre>Ateliê Exemplo A | rascunho | data a definir | revisar contexto antes de qualquer contato
Ateliê Exemplo B | proposta em preparação | data a definir | conferir uso e prazo
Ateliê Exemplo C | encerrado | data a definir | nenhum novo contato; pedido respeitado</pre><p>Guarde somente informações profissionais necessárias. Não registre interesse, envio ou aprovação que não aconteceu.</p></section>
<section id="final"><h2>Conferência final</h2><ul><li>Oferta em uma frase e escopo.</li><li>Cálculo com custos, taxas e margem identificados.</li><li>Três pacotes e proposta de estudo.</li><li>Três peças reais revisadas e PDF que abre.</li><li>Plano de sete dias ajustado à capacidade.</li><li>Vinte abordagens consultadas e três rascunhos adaptados.</li><li>Registro fictício de acompanhamento.</li><li>Perguntas de formalização e permissões pendentes.</li><li>Próxima ação com data e critério.</li></ul><p>Preparação concluída não significa cliente, receita ou negócio validado. Marque o que realmente existe.</p></section>'''
for i,d in enumerate(json.loads((R/'context/aulas-editoriais.json').read_text()),1):body+=f'<section id="aula-{i}"><h2>Aula {i} · {E(d["titulo"])}</h2><pre>{E(d["molde"])}</pre></section>'
body+='<section><h2>Fontes oficiais · consulta em 25/09/2026</h2><ul>'+''.join(f'<li><a href="{E(u)}" target="_blank" rel="noopener">{E(t)}</a></li>' for u,t in json.loads((R/'context/fontes.json').read_text()))+'</ul></section>'
page('caderno.html','Da oferta à proposta conferível',body)
